[package]
name = "lumo"
version = "0.2.4"
description = "CPU based rendering engine"
license = "MIT"
repository = "https://github.com/ekarpp/lumo"
authors = ["ekarpp <eetu@karppinen.xyz>"]
keywords = ["rendering", "path-tracing", "graphics", "3D", "ray-tracing"]
categories = ["graphics", "rendering::engine", "multimedia::images"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = 3
#rustflags = ["-C", "target-cpu=native"]

[profile.dev]
opt-level = 2

[profile.test]
opt-level = 2

[dependencies]
argh = "0.1.10"
glam = "0.23.0"
itertools = "0.10.5"
png = "0.17.7"
rand = "0.8.5"
rayon = "1.7.0"
tempfile = "3.4.0"
ureq = "2.6.2"
zip = "0.6.4"
