[package]
name = "rust_tracer"
version = "0.1.0"
authors = ["ekarpp <eetu@karppinen.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
png = "0.17.7"
rayon = "1.7.0"
