[package]
name = "rust_tracer"
version = "0.1.0"
description = "Path tracer written in rust"
repository = "https://github.com/ekarpp/rust_tracer"
authors = ["ekarpp <eetu@karppinen.xyz>"]
keywords = ["rendering", "path-tracing", "graphics"]
categories = ["graphics", "rendering::engine", ]
edition = "2018"

[profile.release]
codegen-units = 1
lto = "y"

[profile.dev]
opt-level = 2

[dev-dependencies]
ureq = "2.6.2"
zip = "0.6.4"

[dependencies]
glam = "0.23.0"
itertools = "0.10.5"
png = "0.17.7"
rand = "0.8.5"
rayon = "1.7.0"
