[package]
name = "rust_tracer"
version = "0.1.0"
description = "Path tracer written in rust"
repository = "https://github.com/ekarpp/rust_tracer"
authors = ["ekarpp <eetu@karppinen.xyz>"]
keywords = ["rendering", "path-tracing", "graphics"]
categories = ["graphics", "rendering::engine", ]
edition = "2018"

[dependencies]
glam = "0.23.0"
itertools = "0.10.5"
png = "0.17.7"
rand = "0.8.5"
rayon = "1.7.0"
