name: rust_tracer_pipe

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
