name: unit_tests

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
